apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: dropwatch
  name: dropwatch
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dropwatch
  template:
    metadata:
      labels:
        app: dropwatch
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - command:
        - /usr/local/bin/bpftrace
        - /programs/tcpdrop.bt
        image: feisky/dropwatch:bpftrace
        imagePullPolicy: Always
        name: dropwatch
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          privileged: true
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /usr/src
          name: usr-src
          readOnly: true
        - mountPath: /lib/modules
          name: modules-host
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /usr/src
          type: ""
        name: usr-src
      - hostPath:
          path: /lib/modules
          type: ""
        name: modules-host
      - hostPath:
          path: /sys
          type: ""
        name: sys