name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup
      run: |
        sudo apt-get install -y make clang llvm libelf-dev
    - name: Build
      run: |
        make libbpf
        make
